// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"go-webapi-template/internal/app"
	"go-webapi-template/internal/app/controllers"
	"go-webapi-template/internal/domain/services"
	"go-webapi-template/internal/infra/repos"
	services2 "go-webapi-template/internal/infra/services"
	"go-webapi-template/pkg/common"
)

// Injectors from wire.go:

func InitializeFiberApp() common.IApp {
	configurationFilePath := GetConfigurationFilePath()
	configuration := common.LoadConfigurationFromJsonFile(configurationFilePath)
	config := app.ConfigureFiber()
	ctxRequestCallbackFunc := app.ProcessRequestLoggingFuncProvider()
	loggerProvider := app.NewLoggerProvider(configuration)
	ctxResponseCallbackFunc := app.ProcessResponseLoggingFuncProvider(loggerProvider)
	fiberRequestResponseHookMiddleware := common.NewFiberRequestResponseHookMiddleware(ctxRequestCallbackFunc, ctxResponseCallbackFunc)
	iHelloWorldRepository := repos.NewHelloWorldRepository()
	helloWorldService := services.NewHelloWorldService(iHelloWorldRepository)
	helloWorldController := controllers.NewHelloWorldController(helloWorldService)
	client := app.NewHttpClient()
	iProductsServiceProvider := services2.NewApiEmployeesServiceProvider(client)
	productsController := controllers.NewProductsController(iProductsServiceProvider)
	configureFiberAppFunc := app.ConfigureFiberRouting(fiberRequestResponseHookMiddleware, helloWorldController, productsController)
	iApp := common.NewFiberApp(configuration, config, configureFiberAppFunc)
	return iApp
}

// wire.go:

// <editor-fold desc="Default configuration file path">
var defaultConfigurationFilePath = common.ConfigurationFilePath("./configs/appsettings.json")

func GetConfigurationFilePath() common.ConfigurationFilePath {
	return defaultConfigurationFilePath
}

var DIContainer = wire.NewSet(

	GetConfigurationFilePath, common.LoadConfigurationFromJsonFile, app.NewLoggerProvider, app.ProcessRequestLoggingFuncProvider, app.ProcessResponseLoggingFuncProvider, common.NewFiberRequestResponseHookMiddleware, app.NewHttpClient, app.ConfigureFiber, app.ConfigureFiberRouting, common.NewFiberApp, repos.NewHelloWorldRepository, services.NewHelloWorldService, services2.NewApiEmployeesServiceProvider, controllers.NewHelloWorldController, controllers.NewProductsController,
)
